---
abstract: 'Make sure no Smart::Comments escape into the wild'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-NoSmartComments
requires:
  Module::ScanDeps: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/RsrchBoy/Test-NoSmartComments/issues
  repository: git://github.com/RsrchBoy/Test-NoSmartComments.git
version: 0.001
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.14
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: ConsistentVersionTest
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: CompileTests
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: HasVersionTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: PortabilityTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 0.02
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: ReportVersions
      version: 1.110730
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: 1.004
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: ArchiveRelease
      version: 3.01
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.002
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: GitHub::Meta
      version: 0.06
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: GitHub::Update
      version: 0.06
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmePodInRoot
      version: 0.103522
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
x_authority: cpan:RSRCHBOY
